### PR TITLE
Updated to JSDuck 3.10.5 and added various new configuration options

### PR DESCRIPTION
**Pull request by whittlec**
Upgraded JSDuck version to the latest and exposed various new configuration options to Maven projects.

Added support for including guides, a welcome page, a configurable title and header, better display for types with long names, support for multiple source trees to be included in the documentation, and support for documenting the built-in classes.

### CODE REVIEW

**Comment by SebTardif** [comment]
Looks like good stuff but jsduck is now at version 4.1.1

If we could easily choose the version of jsduck that would be useful.

**Comment by whittlec** [comment]
I think we did have to make some small changes to the code that invoked JSDuck itself when we updated it to 3.10.5. This might be a minor complication for supporting configurable JSDuck versions. Admittedly, it was a very old version of JSDuck beforehand.

Do you think we could get JSDuck dynamically using _gem_ might be the way to go here? It seems overkill if we were to embed different JSDuck versions in this plug-in.

**Comment by SebTardif** [comment]
The plug-in could try to not need to modify JSDuck by asking JSDuck project to provide appropriate hooks as need.

Then when it's the case, we could just specify the Git tag/branch/SHA to get the plug-in use the right JSDuck version from GitHub.

I like that the plug-in run under Java without extra install.

**Comment by SebTardif** [comment]
I'm not sure if it's this fork that create the issue but if you open the integration test documentation generated you will get many missing resources:

Failed to load resource file:///D:/repos/git/maven-jsduck/maven-jsduck/target/it/basic/target/jsduck-api/extjs/resources/themes/images/default/form/trigger.gif
Failed to load resource file:///D:/repos/git/maven-jsduck/maven-jsduck/target/it/basic/target/jsduck-api/extjs/resources/themes/images/default/form/exclamation.gif
Failed to load resource file:///D:/repos/git/maven-jsduck/maven-jsduck/target/it/basic/target/jsduck-api/extjs/resources/themes/images/default/grid/grid3-hd-btn.gif
Failed to load resource file:///D:/repos/git/maven-jsduck/maven-jsduck/target/it/basic/target/jsduck-api/extjs/resources/themes/images/default/form/checkbox.gif
GET file:///D:/repos/git/maven-jsduck/maven-jsduck/target/it/basic/target/jsduck-api/extjs/resources/themes/images/default/grid/loading.gif  ext-all.js:21
GET file:///D:/repos/git/maven-jsduck/maven-jsduck/target/it/basic/target/jsduck-api/extjs/resources/themes/images/default/button/arrow.gif  ext-all.js:21

In seems that most of the framework expect to see resources as sibling of extjs but some wants it under extjs folder.

**Pull request merged**
